apiVersion: batch/v1
kind: Job
metadata:
  generateName: spot-job-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue-ks
spec:
  parallelism: 3
  completions: 3
  template:
    spec:
      nodeSelector:
         instance: spot
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["80s"]
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
          limits:
            memory: "200Mi"
            cpu: 1
      restartPolicy: Never
