apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: cluster2-bp
spec:
  wantSingletonReportedState: true
  clusterSelectors:
  - matchLabels:
      name: cluster2
  downsync:
  - objectSelectors:
    - matchLabels: 
        kubestellar.io/cluster: cluster2