apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: cluster1-bp
spec:
  wantSingletonReportedState: true
  clusterSelectors:
  - matchLabels:
      name: cluster1
  downsync:
  - objectSelectors:
    - matchLabels:
        kubestellar.io/cluster: cluster1
