builds:
- id: "cluster-metrics"
  dir: clustermetrics
  main: ./cmd/cluster-metrics
  binary: bin/cluster-metrics
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
- id: "kueue-ks"
  dir: kueue-ks
  main: ./cmd/kueue-ks
  binary: bin/kueue-ks
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
- id: "mc-scheduling"
  dir: mc-scheduling
  main: ./cmd/mc-scheduler
  binary: bin/mc-scheduler
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
- id: "shadow-pods"
  dir: shadow-pods
  main: ./cmd/shadow-pods
  binary: bin/shadow-pods
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
- id: "loki-logger"
  dir: shadow-pods
  main: ./cmd/loki-logger
  binary: bin/loki-logger
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
- id: "suspend-webhook"
  dir: suspend-webhook
  main: ./cmd/suspend-webhook
  binary: bin/suspend-webhook
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
kos:
  - repository: ghcr.io/kubestellar/galaxy/cluster-metrics
    working_dir: clustermetrics
    main: ./cmd/cluster-metrics
    id: cluster-metrics
    build: cluster-metrics
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
  - repository: ghcr.io/kubestellar/galaxy/kueue-ks
    working_dir: kueue-ks
    main: ./cmd/kueue-ks
    id: kueue-ks
    build: kueue-ks
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
  - repository: ghcr.io/kubestellar/galaxy/mc-scheduler
    working_dir: mc-scheduling
    main: ./cmd/mc-scheduler
    id: mc-scheduling
    build: mc-scheduling
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
  - repository: ghcr.io/kubestellar/galaxy/shadow-pods
    working_dir: shadow-pods
    main: ./cmd/shadow-pods
    id: shadow-pods
    build: shadow-pods
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
  - repository: ghcr.io/kubestellar/galaxy/loki-logger
    working_dir: shadow-pods
    main: ./cmd/loki-logger
    id: loki-logger
    build: loki-logger
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
  - repository: ghcr.io/kubestellar/galaxy/suspend-webhook
    working_dir: suspend-webhook
    main: ./cmd/suspend-webhook
    id: suspend-webhook
    build: suspend-webhook
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
release:
  draft: false
  prerelease: auto
  mode: keep-existing
