apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: cluster1
spec:
  clusterSelectors:
  - matchLabels:
      name: cluster1
      location-group: edge
  downsync:
  - objectSelectors:
    - matchLabels:
        kubestellar.io/cluster: cluster1
  wantSingletonReportedState: true	