apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: kueue-bp
spec:
  clusterSelectors:
  - matchLabels:
      location-group: edge
  downsync:
  - createOnly: true
    objectSelectors:
    - matchLabels:
        app.kubernetes.io/name: kueue
