apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-controller-manager
  namespace: kueue-ks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-leader-election-role
  namespace: kueue-ks-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - tenancy.kflex.kubestellar.org
  resources:
  - controlplanes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-kueue-ks-editor-role
rules:
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics/status
  verbs:
  - get
- apiGroups:
  - control.kubestellar.io
  resources:
  - bindingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - admissionchecks
  - workloads
  - clusterqueues
  - localqueues
  - resourceflavors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - admissionchecks/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - workloads/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  - pytorchjobs/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - tenancy.kflex.kubestellar.org
  resources:
  - controlplanes
  verbs:
  - get
  - list
- apiGroups:
  - control.kubestellar.io
  resources:
  - combinedstatuses
  - combinedstatuses/results
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-kueue-ks-viewer-role
rules:
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics/status
  verbs:
  - get
- apiGroups:
  - control.kubestellar.io
  resources:
  - bindingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - admissionchecks
  - workloads
  - clusterqueues
  - localqueues
  - resourceflavors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - admissionchecks/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - workloads/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  - pytorchjobs/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - tenancy.kflex.kubestellar.org
  resources:
  - controlplanes
  verbs:
  - get
  - list
- apiGroups:
  - control.kubestellar.io
  resources:
  - combinedstatuses
  - combinedstatuses/results
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - control.kubestellar.io
  resources:
  - combinedstatuses
  - combinedstatuses/results
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics/finalizers
  verbs:
  - update
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - control.kubestellar.io
  resources:
  - bindingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - admissionchecks
  - workloads
  - clusterqueues
  - localqueues
  - resourceflavors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - admissionchecks/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - workloads/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - delete
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - pytorchjobs
  - pytorchjobs/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - tenancy.kflex.kubestellar.org
  resources:
  - controlplanes
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-leader-election-rolebinding
  namespace: kueue-ks-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kueue-ks-leader-election-role
subjects:
- kind: ServiceAccount
  name: kueue-ks-controller-manager
  namespace: kueue-ks-system
- kind: User
  name: system:serviceaccount:open-cluster-management-agent:klusterlet-work-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-ks-controller-manager
subjects:
- kind: ServiceAccount
  name: kueue-ks-controller-manager
  namespace: kueue-ks-system
- kind: User
  name: system:serviceaccount:open-cluster-management-agent:klusterlet-work-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
  name: kueue-ks-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-ks-proxy-role
subjects:
- kind: ServiceAccount
  name: kueue-ks-controller-manager
  namespace: kueue-ks-system
- kind: User
  name: system:serviceaccount:open-cluster-management-agent:klusterlet-work-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kueue-ks
    control-plane: controller-manager
  name: kueue-ks-controller-manager-metrics-service
  namespace: kueue-ks-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
