apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
  name: clustermetrics-controller-manager
  namespace: clustermetrics-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
  name: clustermetrics-leader-election-role
  namespace: clustermetrics-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
  name: clustermetrics-clustermetrics-editor-role
rules:
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
  name: clustermetrics-clustermetrics-viewer-role
rules:
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustermetrics-manager-role
  labels:
    app.kubernetes.io/name: clustermetrics

rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics/finalizers
  verbs:
  - update
- apiGroups:
  - galaxy.kubestellar.io
  resources:
  - clustermetrics/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
  name: clustermetrics-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
  name: clustermetrics-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
  name: clustermetrics-leader-election-rolebinding
  namespace: clustermetrics-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clustermetrics-leader-election-role
subjects:
- kind: ServiceAccount
  name: clustermetrics-controller-manager
  namespace: clustermetrics-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
  name: clustermetrics-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clustermetrics-manager-role
subjects:
- kind: ServiceAccount
  name: clustermetrics-controller-manager
  namespace: clustermetrics-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
  name: clustermetrics-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clustermetrics-proxy-role
subjects:
- kind: ServiceAccount
  name: clustermetrics-controller-manager
  namespace: clustermetrics-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clustermetrics
    control-plane: controller-manager
  name: clustermetrics-controller-manager-metrics-service
  namespace: clustermetrics-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
