apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue-ks"
spec:
  preemption:
    reclaimWithinCohort: Any
    borrowWithinCohort:
      policy: LowerPriority
      maxPriorityThreshold: 100
    withinClusterQueue: LowerPriority
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu","memory","gpu"]
    flavors:
    - name: "h100"
      resources:
      - name: "cpu"
        nominalQuota: 24
      - name: "memory"
        nominalQuota: 16Gi
      - name: "gpu"
        nominalQuota: 0
    - name: "a100"
      resources:
      - name: "cpu"
        nominalQuota: 0
      - name: "memory"
        nominalQuota: 0Gi
      - name: "gpu"
        nominalQuota: 0
    - name: "spot"
      resources:
      - name: "cpu"
        nominalQuota: 30
      - name: "memory"
        nominalQuota: 24Gi
      - name: "gpu"
        nominalQuota: 0

  admissionChecks:
  - kubestellar-admc
