apiVersion: v1
kind: Service
metadata:
  annotations:
    app: loki
  name: loki-nodeport
  namespace: loki
spec:
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: loki
    release: loki
  sessionAffinity: None
  type: NodePort
