apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: workflows-cluster2
spec:
  wantSingletonReportedState: true
  clusterSelectors:
  - matchLabels:
      name: cluster2
  downsync:
  - objectSelectors:
    - matchLabels:
        kubestellar.io/cluster: cluster2
