name: goreleaser

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write
  packages: write
 
env:
  REGISTRY: ghcr.io
  REPO: kubestellar/galaxy
  CHARTS_PATH: ./charts

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: v1.19

    - name: Delete non-semver tags
      run: 'git tag -d $(git tag -l | grep -v "^v")'

    - name: Set LDFLAGS
      run: echo LDFLAGS="$(make ldflags)" >> $GITHUB_ENV

    - name: Run GoReleaser on tag
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --timeout 60m --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USER: ${{ github.actor }}
        EMAIL: ${{ github.actor}}@users.noreply.github.com

    - name: Set up Helm
      uses: azure/setup-helm@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Package and push clustermetrics chart
      run: |    
        cd clustermetrics && make chart IMG=${{ env.REGISTRY }}/${{ env.REPO }}/cluster-metrics:${{github.ref_name}} && cd -
        helm package ${{ env.CHARTS_PATH }}/cluster-metrics --destination . --version ${{github.ref_name}} --app-version ${{github.ref_name}}
        helm push ./cluster-metrics-${{github.ref_name}}.tgz oci://${{ env.REGISTRY }}/${{ env.REPO }}  

    - name: Package and push mc-scheduling chart
      run: |    
        cd mc-scheduling && make chart IMG=${{ env.REGISTRY }}/${{ env.REPO }}/mc-scheduler:${{github.ref_name}} && cd -
        helm package ${{ env.CHARTS_PATH }}/mc-scheduling --destination . --version ${{github.ref_name}} --app-version ${{github.ref_name}}
        helm push ./mc-scheduling-${{github.ref_name}}.tgz oci://${{ env.REGISTRY }}/${{ env.REPO }}  
    
    - name: Package and push shadow-pods chart
      run: |    
        cd mc-scheduling && make chart IMG=${{ env.REGISTRY }}/${{ env.REPO }}/mc-scheduler:${{github.ref_name}} && cd -
        helm package ${{ env.CHARTS_PATH }}/mc-scheduling --destination . --version ${{github.ref_name}} --app-version ${{github.ref_name}}
        helm push ./mc-scheduling-${{github.ref_name}}.tgz oci://${{ env.REGISTRY }}/${{ env.REPO }}  
        
